filter:
    excluded_paths:
        - 'app/*'
        - 'bin/*'
        - 'src/AppBundle/Tests/*'
checks:
    php: true
coding_style:
    php: {  }
tools:
    external_code_coverage:
        timeout: 600
