language: php

php: 7.0

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - mkdir app/data

install:
  - composer install
  - bin/console doctrine:schema:create
  - echo y | bin/console fixtures:load
  - bin/console server:start

script: phpunit --configuration phpunit.xml.dist --coverage-text

notifications:
  on_success: never
  on_failure: never
