language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php: 7.0

before_script:
  - composer self-update
  - composer install
  - bin/console doctrine:schema:create --env=test
  - echo y | bin/console fixtures:load --env=test
  - bin/console server:start

script: vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover

after_script:
  - bin/console server:stop
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - vendor/bin/php-cs-fixer fix --diff --dry-run -v

notifications:
  email: false
