user_list:
    path: /users
    methods: GET
    defaults: { _controller: user_controller.list:getAction }

user_details:
    path: /users/{userId}
    defaults: { _controller: user_controller.details:getAction }

user_create:
    path: /users
    methods: POST
    defaults: { _controller: user_controller.create:postAction }
