user_list:
    path: /users
    defaults: { _controller: user_controller.list:getAction }

user_details:
    path: /users/{userId}
    defaults: { _controller: user_controller.details:getAction }

user_create:
    path: /users
    defaults: { _controller: user_controller:newUserAction }
