services:
    # controllers
    user_controller.list:
        class: AppBundle\Controller\User\ListController
        arguments:
            - '@jms_serializer'
            - '@user_repository'
            - '@pagination_factory'

    user_controller.details:
        class: AppBundle\Controller\User\DetailsController
        arguments:
            - '@jms_serializer'
            - '@user_repository'

    user_controller.create:
        class: AppBundle\Controller\User\CreateController
        arguments:
            - '@jms_serializer'
            - '@user_repository'
            - '@form.factory'
            - '@doctrine'
            - '@router'

    # repositories
    user_repository:
        class: AppBundle\Repository\UserRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\User

    # factories
    pagination_factory:
        class: AppBundle\Pagination\PaginationFactory
        arguments:
            - '@router'

    # serializer
    link_serialization_subscriber:
        class: AppBundle\Serializer\LinkSerializationSubscriber
        arguments:
            - '@router'
            - '@annotation_reader'
        tags:
            - { name: jms_serializer.event_subscriber }
